name: Daily Update Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 4 * *"
    

env:
  TZ: Asia/Shanghai

jobs:
  VisionFive-Buildroot:
    runs-on: ubuntu-latest
    name: VisionFive Buildroot Last Commit Check
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Checkout
      uses: actions/checkout@main
      with:
        repository: buildroot/buildroot
        path: buildroot
    
    - name: Check Commit ID
      id: truecommit
      working-directory: ${{ github.workspace }}/buildroot
      run: |
        echo "shortid=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
        echo "longid=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
        echo "message=$(git log -1)" >> message.log

    - name: Calculate Time Difference
      id: time
      working-directory: ${{ github.workspace }}/buildroot
      run: |
        echo "duration=$(( $(date +%s) - $(git log --pretty=format:'%cd' --date=unix -1) ))" >> "$GITHUB_OUTPUT"
    
    - name: Call Build Workflow
      id: call 
      if: steps.time.outputs.duration <= 86400
      uses: ./.github/workflows/VisionFive-Buildroot.yaml
    
    - name: Output Success Summary
      if: steps.call.conclusion == 'success'
      run: |
        echo "# VisionFive Buildroot Last Commit Check" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "[CI ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) has successfully triggered a VisionFive Buildroot image CI build powered by [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}) since last commit is within 24 hours." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Commit Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "CI has built on commit [${{ steps.truecommit.outputs.shortid }}](https://git.busybox.net/buildroot/commit/id=${{ steps.truecommit.outputs.longid }}). The commit message is shown below." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "```bash" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/buildroot/message.log >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

    - name: Output Success Summary
      if: steps.call.conclusion == 'skip'
      run: |
        echo "# VisionFive Buildroot Last Commit Check" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "[CI ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) has successfully checked VisionFive Buildroot powered by [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}). However, it did not trigger a build CI since the last commit was 24 hours away." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Commit Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "CI has built on commit [${{ steps.truecommit.outputs.shortid }}](https://git.busybox.net/buildroot/commit/id=${{ steps.truecommit.outputs.longid }}). The commit message is shown below." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "```bash" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/buildroot/message.log >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY