name: Bulid VisionFive Buildroot Image

on:
  workflow_dispatch:
  workflow_call:
    

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        repository: buildroot/buildroot

    - name: Initialization Environment
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio python3 unzip rsync file bc wget g++-multilib
        sudo timedatectl set-timezone "$TZ"
    
    - name: Check Commit ID
      id: truecommit
      run: |
        echo "shortid=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
        echo "longid=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
        echo "message=$(git log -1)" >> message.log

    - name: Make Config
      run: make visionfive_defconfig | tee config.log

    - name: Make Image
      id: imagegen
      run: make -j$(nproc) | tee build.log

    - name: Check Image Path
      id: imgpath
      run: |
        ls
        echo "path=$(ls ${{ github.workspace }}/output/images/sdcard.img)" >> "$GITHUB_OUTPUT"

    - name: Generate Hash
      id: hash
      run: echo "sha256=$(sha256sum ${{ steps.imgpath.outputs.path }})" >> "$GITHUB_OUTPUT"

    - name: Upload Image
      uses: actions/upload-artifact@main
      with:
        name: VisionFive-Buildroot-${{ steps.truecommit.outputs.shortid }}-Image
        path: ${{ steps.imgpath.outputs.path }}
        if-no-files-found: error
    
    - name: Upload Log
      uses: actions/upload-artifact@main
      with:
        name: VisionFive-Buildroot-${{ steps.truecommit.outputs.shortid }}-Log
        path: |
          config.log
          build.log
    
    - name: Output Success Summary
      if: steps.imagegen.conclusion == 'success'
      run: |
        echo "# Bulid VisionFive Buildroot Image" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "[CI ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) has successfully built the VisionFive Buildroot image powered by [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Commit Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "CI has built on commit [${{ steps.truecommit.outputs.shortid }}](https://git.busybox.net/buildroot/commit/id=${{ steps.truecommit.outputs.longid }}). The commit message is shown below." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "```bash" >> $GITHUB_STEP_SUMMARY
        cat message.log >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Artifacts Hash" >> $GITHUB_STEP_SUMMARY
        echo "```bash" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.hash.outputs.sha256 }}" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        echo "## Build Log" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Last 100 Lines of Config Log" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "```bash" >> $GITHUB_STEP_SUMMARY
        tail -100 config.log
        echo "```" >> $GITHUB_STEP_SUMMARY
        echo "### Last 100 Lines of Build Log" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "```bash" >> $GITHUB_STEP_SUMMARY
        tail -100 build.log
        echo "```" >> $GITHUB_STEP_SUMMARY